### PR TITLE
Initial horsification

### PR DESCRIPTION
**Pull request by ajacksified**
Break out core libraries into `horse` and `horse-react` external libraries. Switch from `express` to `koa` because generators are hipster.

### CODE REVIEW

**Comment by ajacksified** [comment]
:eyeglasses: @danehansen @btholt

**Comment by ajacksified** [comment]
regressions:

* [ ] 'forward' in browser history fails
* [ ] initial load still fires an extra api request

**Comment by ajacksified** [comment]
After this, we will be renaming this to `reddit-mobile`, and the plugins to `reddit-mobile-plugin-ads` and `reddit-mobile-plugin-metrics`, and deleting `switcharoo-plugin-core`, which has been merged.

**Comment by danehansen** [comment]
:fish:

**Comment by limmmster** [comment]
:upvote:

**Pull request merged**
